import { useState, useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { Filter, Save, X, Check, Trash2, Pencil, Bookmark, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { HijriDatePicker } from "@/components/ui/hijri-date-picker";
import {
  MemoType,
  MemoTypeLabels,
  MemoStatus,
  MemoStatusLabels,
  CaseClassification,
  CaseClassificationLabels,
} from "@shared/schema";

export type AdvancedMemosFilters = {
  memoTypes: string[];
  statuses: string[];
  priorities: string[];
  depts: string[];
  lawyers: string[];           // matches against memo.assignedTo
  classification: string;       // "" | "قيد_الدراسة" | "منظورة_بالمحكمة"
  deadlineFrom: string;         // "" | YYYY-MM-DD (Gregorian)
  deadlineTo: string;
  overdueOnly: boolean;
  autoGeneratedOnly: boolean;
};

export const EMPTY_MEMOS_ADV_FILTERS: AdvancedMemosFilters = {
  memoTypes: [],
  statuses: [],
  priorities: [],
  depts: [],
  lawyers: [],
  classification: "",
  deadlineFrom: "",
  deadlineTo: "",
  overdueOnly: false,
  autoGeneratedOnly: false,
};

// Memo statuses considered "still in motion" — used by the overdue check.
export const NON_FINAL_MEMO_STATUSES: ReadonlySet<string> = new Set([
  "لم_تبدأ",
  "قيد_التحرير",
  "قيد_المراجعة",
  "بانتظار_الاعتماد",
  "تحتاج_تعديل",
]);

export function countActiveMemosAdvFilters(f: AdvancedMemosFilters): number {
  return (
    (f.memoTypes.length > 0 ? 1 : 0) +
    (f.statuses.length > 0 ? 1 : 0) +
    (f.priorities.length > 0 ? 1 : 0) +
    (f.depts.length > 0 ? 1 : 0) +
    (f.lawyers.length > 0 ? 1 : 0) +
    (f.classification ? 1 : 0) +
    (f.deadlineFrom ? 1 : 0) +
    (f.deadlineTo ? 1 : 0) +
    (f.overdueOnly ? 1 : 0) +
    (f.autoGeneratedOnly ? 1 : 0)
  );
}

const RECENT_KEY = "memos.recentFilters.v1";
const RECENT_MAX = 5;

const LAWYER_FILTER_EXCLUDED_ROLES = new Set([
  "branch_manager",
  "admin_support",
  "hr",
  "technical_support",
]);

type SavedFilterRow = {
  id: string;
  name: string;
  filterConfig: AdvancedMemosFilters;
  pageType: string;
  createdAt: string;
};

function loadRecent(): AdvancedMemosFilters[] {
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveRecent(f: AdvancedMemosFilters) {
  if (countActiveMemosAdvFilters(f) === 0) return;
  try {
    const existing = loadRecent();
    const key = JSON.stringify(f);
    const dedup = existing.filter((e) => JSON.stringify(e) !== key);
    const next = [f, ...dedup].slice(0, RECENT_MAX);
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  } catch {
    // localStorage failures shouldn't break filtering
  }
}

interface MultiSelectComboProps {
  label: string;
  values: string[];
  onChange: (values: string[]) => void;
  options: Array<{ value: string; label: string }>;
  placeholder?: string;
  searchable?: boolean;
  testIdPrefix?: string;
}

function MultiSelectCombo({
  label,
  values,
  onChange,
  options,
  placeholder,
  searchable = true,
  testIdPrefix,
}: MultiSelectComboProps) {
  const [open, setOpen] = useState(false);
  const toggle = (value: string) => {
    if (values.includes(value)) onChange(values.filter((v) => v !== value));
    else onChange([...values, value]);
  };
  const summary =
    values.length === 0
      ? placeholder || "اختر..."
      : values.length === 1
        ? options.find((o) => o.value === values[0])?.label || values[0]
        : `${values.length} محدد`;

  return (
    <div className="space-y-1">
      <Label className="text-xs text-muted-foreground">{label}</Label>
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            className="w-full justify-between font-normal"
            data-testid={testIdPrefix ? `${testIdPrefix}-trigger` : undefined}
          >
            <span className={values.length === 0 ? "text-muted-foreground" : ""}>{summary}</span>
            {values.length > 0 && (
              <Badge variant="secondary" className="mr-2 h-5">{values.length}</Badge>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-[260px] p-0" align="start">
          <Command>
            {searchable && <CommandInput placeholder="بحث..." />}
            <CommandList>
              <CommandEmpty>لا توجد نتائج</CommandEmpty>
              <CommandGroup>
                {options.map((opt) => {
                  const selected = values.includes(opt.value);
                  return (
                    <CommandItem
                      key={opt.value}
                      value={opt.label}
                      onSelect={() => toggle(opt.value)}
                      data-testid={testIdPrefix ? `${testIdPrefix}-option-${opt.value}` : undefined}
                    >
                      <div className="flex items-center gap-2 flex-1">
                        <div
                          className={
                            "h-4 w-4 rounded border flex items-center justify-center " +
                            (selected ? "bg-primary border-primary text-primary-foreground" : "border-input")
                          }
                        >
                          {selected && <Check className="h-3 w-3" />}
                        </div>
                        <span>{opt.label}</span>
                      </div>
                    </CommandItem>
                  );
                })}
              </CommandGroup>
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
    </div>
  );
}

interface UserLite {
  id: string;
  name: string;
  role: string;
  departmentId: string | null;
}

interface Props {
  filters: AdvancedMemosFilters;
  onChange: (filters: AdvancedMemosFilters) => void;
  departments: Array<{ id: string; name: string }>;
  users: UserLite[];
}

export function MemosAdvancedFilters({ filters, onChange, departments, users }: Props) {
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState<AdvancedMemosFilters>(filters);
  const [savedName, setSavedName] = useState("");
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const [recents, setRecents] = useState<AdvancedMemosFilters[]>([]);
  const { toast } = useToast();

  useEffect(() => {
    if (open) {
      setDraft(filters);
      setRecents(loadRecent());
    }
  }, [open, filters]);

  const savedQuery = useQuery<SavedFilterRow[]>({
    queryKey: ["/api/saved-filters", "?pageType=memos"],
    queryFn: async () => {
      const res = await apiRequest("GET", "/api/saved-filters?pageType=memos");
      return res.json();
    },
    enabled: open,
  });

  const memoTypeOptions = useMemo(
    () =>
      Object.values(MemoType).map((v) => ({
        value: v,
        label: MemoTypeLabels[v as keyof typeof MemoTypeLabels] || v,
      })),
    [],
  );
  const statusOptions = useMemo(
    () =>
      Object.values(MemoStatus).map((v) => ({
        value: v,
        label: MemoStatusLabels[v as keyof typeof MemoStatusLabels] || v,
      })),
    [],
  );
  const priorityOptions = useMemo(
    () =>
      ["عاجل", "عالي", "متوسط", "منخفض"].map((v) => ({ value: v, label: v })),
    [],
  );
  const deptOptions = useMemo(
    () => departments.map((d) => ({ value: String(d.id), label: d.name })),
    [departments],
  );

  // Lawyer narrows by selected departments. Same role-based exclusion as
  // cases/hearings filters.
  const lawyerOptions = useMemo(() => {
    const eligible = users.filter((u) => !LAWYER_FILTER_EXCLUDED_ROLES.has(u.role));
    const scoped =
      draft.depts.length === 0
        ? eligible
        : eligible.filter((u) => u.departmentId && draft.depts.includes(u.departmentId));
    return scoped.map((u) => ({ value: u.id, label: u.name }));
  }, [users, draft.depts]);

  useEffect(() => {
    const allowed = new Set(lawyerOptions.map((o) => o.value));
    if (draft.lawyers.some((id) => !allowed.has(id))) {
      setDraft((prev) => ({
        ...prev,
        lawyers: prev.lawyers.filter((id) => allowed.has(id)),
      }));
    }
  }, [lawyerOptions, draft.lawyers]);

  const deptNameById = (id: string) => departments.find((d) => String(d.id) === id)?.name || id;
  const userNameById = (id: string) => users.find((u) => u.id === id)?.name || id;

  const apply = (next: AdvancedMemosFilters) => {
    onChange(next);
    saveRecent(next);
    setRecents(loadRecent());
    setOpen(false);
  };

  const clearAll = () => setDraft(EMPTY_MEMOS_ADV_FILTERS);
  const handleApplyDraft = () => apply(draft);

  const handleSaveCurrent = async () => {
    const name = savedName.trim();
    if (!name) {
      toast({ title: "أدخل اسماً للفلتر", variant: "destructive" });
      return;
    }
    if (countActiveMemosAdvFilters(draft) === 0) {
      toast({ title: "لا توجد فلاتر مختارة لحفظها", variant: "destructive" });
      return;
    }
    try {
      await apiRequest("POST", "/api/saved-filters", {
        name,
        filterConfig: draft,
        pageType: "memos",
      });
      setSavedName("");
      queryClient.invalidateQueries({ queryKey: ["/api/saved-filters", "?pageType=memos"] });
      toast({ title: "تم حفظ الفلتر" });
    } catch (e: any) {
      toast({ title: "فشل حفظ الفلتر", description: e?.message, variant: "destructive" });
    }
  };

  const handleDeleteSaved = async (id: string) => {
    try {
      await apiRequest("DELETE", `/api/saved-filters/${id}`);
      queryClient.invalidateQueries({ queryKey: ["/api/saved-filters", "?pageType=memos"] });
      toast({ title: "تم حذف الفلتر" });
    } catch (e: any) {
      toast({ title: "فشل الحذف", description: e?.message, variant: "destructive" });
    }
  };

  const handleRenameSaved = async (id: string) => {
    const name = renameValue.trim();
    if (!name) return;
    try {
      await apiRequest("PATCH", `/api/saved-filters/${id}`, { name });
      setRenamingId(null);
      setRenameValue("");
      queryClient.invalidateQueries({ queryKey: ["/api/saved-filters", "?pageType=memos"] });
      toast({ title: "تم تعديل الاسم" });
    } catch (e: any) {
      toast({ title: "فشل التعديل", description: e?.message, variant: "destructive" });
    }
  };

  const describeFilters = (f: AdvancedMemosFilters): string => {
    const parts: string[] = [];
    if (f.memoTypes.length)
      parts.push(`النوع: ${f.memoTypes.map((t) => MemoTypeLabels[t as keyof typeof MemoTypeLabels] || t).join("، ")}`);
    if (f.statuses.length)
      parts.push(`الحالة: ${f.statuses.map((s) => MemoStatusLabels[s as keyof typeof MemoStatusLabels] || s).join("، ")}`);
    if (f.priorities.length) parts.push(`الأولوية: ${f.priorities.join("، ")}`);
    if (f.depts.length) parts.push(`القسم: ${f.depts.map(deptNameById).join("، ")}`);
    if (f.lawyers.length) parts.push(`المسند إليه: ${f.lawyers.map(userNameById).join("، ")}`);
    if (f.classification)
      parts.push(`التصنيف: ${CaseClassificationLabels[f.classification as keyof typeof CaseClassificationLabels] || f.classification}`);
    if (f.deadlineFrom || f.deadlineTo)
      parts.push(`المهلة من ${f.deadlineFrom || "؟"} إلى ${f.deadlineTo || "؟"}`);
    if (f.overdueOnly) parts.push("المتأخرة فقط");
    if (f.autoGeneratedOnly) parts.push("التلقائية فقط");
    return parts.join(" • ") || "—";
  };

  const activeCount = countActiveMemosAdvFilters(filters);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          className="gap-2"
          data-testid="button-memos-advanced-filters"
        >
          <Filter className="h-4 w-4" />
          فلاتر متقدمة
          {activeCount > 0 && (
            <Badge variant="default" className="h-5 px-1.5">{activeCount}</Badge>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[460px] p-0" align="start">
        <div className="p-4 space-y-4 max-h-[80vh] overflow-y-auto">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold">فلاتر متقدمة</h3>
            <Button
              variant="ghost"
              size="sm"
              onClick={clearAll}
              data-testid="button-clear-memos-adv-filters"
            >
              <X className="h-4 w-4 ml-1" />
              مسح
            </Button>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <MultiSelectCombo
              label="نوع المذكرة"
              values={draft.memoTypes}
              onChange={(v) => setDraft({ ...draft, memoTypes: v })}
              options={memoTypeOptions}
              placeholder="كل الأنواع"
              searchable={false}
              testIdPrefix="adv-memo-type"
            />
            <MultiSelectCombo
              label="الحالة"
              values={draft.statuses}
              onChange={(v) => setDraft({ ...draft, statuses: v })}
              options={statusOptions}
              placeholder="كل الحالات"
              searchable={false}
              testIdPrefix="adv-memo-status"
            />
            <MultiSelectCombo
              label="الأولوية"
              values={draft.priorities}
              onChange={(v) => setDraft({ ...draft, priorities: v })}
              options={priorityOptions}
              placeholder="كل الأولويات"
              searchable={false}
              testIdPrefix="adv-memo-priority"
            />
            <MultiSelectCombo
              label="القسم"
              values={draft.depts}
              onChange={(v) => setDraft({ ...draft, depts: v })}
              options={deptOptions}
              placeholder="كل الأقسام"
              testIdPrefix="adv-memo-dept"
            />
            <MultiSelectCombo
              label="المسند إليه"
              values={draft.lawyers}
              onChange={(v) => setDraft({ ...draft, lawyers: v })}
              options={lawyerOptions}
              placeholder={draft.depts.length ? "ضمن الأقسام المختارة" : "كل المسند إليهم"}
              testIdPrefix="adv-memo-lawyer"
            />
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">التصنيف</Label>
              <Select
                value={draft.classification || "all"}
                onValueChange={(v) =>
                  setDraft({ ...draft, classification: v === "all" ? "" : v })
                }
              >
                <SelectTrigger
                  className="w-full h-9"
                  data-testid="select-adv-memos-classification"
                >
                  <SelectValue placeholder="كل التصنيفات" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">كل التصنيفات</SelectItem>
                  <SelectItem value={CaseClassification.UNDER_STUDY}>قضية قيد الدراسة</SelectItem>
                  <SelectItem value={CaseClassification.IN_COURT}>منظورة بالمحكمة</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">المهلة من</Label>
              <HijriDatePicker
                value={draft.deadlineFrom}
                onChange={(v) => setDraft({ ...draft, deadlineFrom: v })}
                placeholder="اختر التاريخ"
                data-testid="input-adv-memo-deadline-from"
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">المهلة إلى</Label>
              <HijriDatePicker
                value={draft.deadlineTo}
                onChange={(v) => setDraft({ ...draft, deadlineTo: v })}
                placeholder="اختر التاريخ"
                data-testid="input-adv-memo-deadline-to"
              />
            </div>
          </div>

          <div className="flex items-center justify-between rounded-md border px-3 py-2">
            <Label htmlFor="adv-memo-overdue" className="text-sm cursor-pointer">
              المتأخرة فقط
            </Label>
            <Switch
              id="adv-memo-overdue"
              checked={draft.overdueOnly}
              onCheckedChange={(v) => setDraft({ ...draft, overdueOnly: v })}
              data-testid="switch-adv-memo-overdue"
            />
          </div>
          <div className="flex items-center justify-between rounded-md border px-3 py-2">
            <Label htmlFor="adv-memo-auto" className="text-sm cursor-pointer">
              المذكرات التلقائية فقط
            </Label>
            <Switch
              id="adv-memo-auto"
              checked={draft.autoGeneratedOnly}
              onCheckedChange={(v) => setDraft({ ...draft, autoGeneratedOnly: v })}
              data-testid="switch-adv-memo-auto"
            />
          </div>

          <div className="flex justify-end">
            <Button size="sm" onClick={handleApplyDraft} data-testid="button-apply-memos-adv-filters">
              تطبيق
            </Button>
          </div>

          <div className="border-t pt-3 space-y-2">
            <div className="flex items-center gap-2 text-sm font-medium">
              <Save className="h-4 w-4" />
              حفظ كفلتر
            </div>
            <div className="flex gap-2">
              <Input
                placeholder="اسم الفلتر"
                value={savedName}
                onChange={(e) => setSavedName(e.target.value)}
                className="flex-1"
                data-testid="input-memos-saved-filter-name"
              />
              <Button
                size="sm"
                variant="secondary"
                onClick={handleSaveCurrent}
                data-testid="button-save-memos-filter"
              >
                حفظ
              </Button>
            </div>
          </div>

          <div className="border-t pt-3 space-y-2">
            <div className="flex items-center gap-2 text-sm font-medium">
              <Bookmark className="h-4 w-4" />
              الفلاتر المحفوظة
            </div>
            {savedQuery.isLoading ? (
              <div className="text-xs text-muted-foreground">جاري التحميل...</div>
            ) : !savedQuery.data || savedQuery.data.length === 0 ? (
              <div className="text-xs text-muted-foreground">لا توجد فلاتر محفوظة</div>
            ) : (
              <ul className="space-y-1">
                {savedQuery.data.map((row) => (
                  <li
                    key={row.id}
                    className="flex items-center justify-between gap-2 rounded border px-2 py-1.5 hover-elevate"
                    data-testid={`memos-saved-filter-${row.id}`}
                  >
                    {renamingId === row.id ? (
                      <>
                        <Input
                          className="h-7 flex-1"
                          value={renameValue}
                          onChange={(e) => setRenameValue(e.target.value)}
                          autoFocus
                          onKeyDown={(e) => {
                            if (e.key === "Enter") handleRenameSaved(row.id);
                            if (e.key === "Escape") {
                              setRenamingId(null);
                              setRenameValue("");
                            }
                          }}
                        />
                        <Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => handleRenameSaved(row.id)}>
                          <Check className="h-4 w-4" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="h-7 w-7"
                          onClick={() => {
                            setRenamingId(null);
                            setRenameValue("");
                          }}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </>
                    ) : (
                      <>
                        <button
                          type="button"
                          className="flex-1 text-right truncate"
                          onClick={() => apply(row.filterConfig || EMPTY_MEMOS_ADV_FILTERS)}
                          title={describeFilters(row.filterConfig || EMPTY_MEMOS_ADV_FILTERS)}
                        >
                          <div className="text-sm font-medium truncate">{row.name}</div>
                          <div className="text-xs text-muted-foreground truncate">
                            {describeFilters(row.filterConfig || EMPTY_MEMOS_ADV_FILTERS)}
                          </div>
                        </button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="h-7 w-7"
                          onClick={() => {
                            setRenamingId(row.id);
                            setRenameValue(row.name);
                          }}
                          data-testid={`button-rename-memos-${row.id}`}
                        >
                          <Pencil className="h-3.5 w-3.5" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="h-7 w-7 text-destructive"
                          onClick={() => handleDeleteSaved(row.id)}
                          data-testid={`button-delete-memos-${row.id}`}
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>

          {recents.length > 0 && (
            <div className="border-t pt-3 space-y-2">
              <div className="flex items-center gap-2 text-sm font-medium">
                <Clock className="h-4 w-4" />
                الأخيرة
              </div>
              <ul className="space-y-1">
                {recents.map((r, idx) => (
                  <li key={idx}>
                    <button
                      type="button"
                      className="w-full text-right rounded border px-2 py-1.5 hover-elevate"
                      onClick={() => apply(r)}
                      data-testid={`memos-recent-filter-${idx}`}
                    >
                      <div className="text-xs text-muted-foreground truncate">
                        {describeFilters(r)}
                      </div>
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </PopoverContent>
    </Popover>
  );
}
